# Generated by Django 3.2.8 on 2021-10-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentirsebien', '0002_dataunfv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataunfv',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
