# Generated by Django 3.2.8 on 2021-10-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentirsebien', '0004_auto_20211021_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='universidad',
            field=models.CharField(blank=True, choices=[('unfv', 'Universidad Nacional Federico Villareal'), ('red_acacia', 'Red Acacia'), ('otros', 'General')], max_length=20, null=True),
        ),
    ]
