# Generated by Django 3.2.8 on 2021-10-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentirsebien', '0005_alter_perfil_universidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='dni',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
