# Generated by Django 3.2.8 on 2021-10-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentirsebien', '0007_dataunfv_anio_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichasociodemografica',
            name='escuela',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fichasociodemografica',
            name='facultad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
