# Generated by Django 3.2.8 on 2021-10-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentirsebien', '0010_alter_fichasociodemografica_nacionalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichasociodemografica',
            name='vive_con',
            field=models.CharField(blank=True, choices=[('solo', 'Solo (a)'), ('pareja', 'Con mi pareja'), ('familia', 'Con mi familia (padres y hermanos)'), ('amigos', 'Con amigos'), ('hermanos', 'Con mis hermanos'), ('parientes', 'Con parientes')], max_length=20, null=True),
        ),
    ]
