# Generated by Django 3.2.8 on 2021-11-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentirsebien', '0011_alter_fichasociodemografica_vive_con'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichasociodemografica',
            name='nacionalidad',
            field=models.CharField(blank=True, choices=[('peru', 'Perú'), ('chile', 'Chile'), ('paraguay', 'Paraguay'), ('colombia', 'Colombia'), ('venezuela', 'Venezuela'), ('otros', 'Otros')], max_length=30, null=True),
        ),
    ]
