# Generated by Django 3.2.8 on 2021-11-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentirsebien', '0012_alter_fichasociodemografica_nacionalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentebienestar',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
