# Generated by Django 3.2.8 on 2021-11-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentirsebien', '0013_componentebienestar_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retroalimentacion',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('topico', models.CharField(choices=[('sa_mental', 'SALUD MENTAL POSITIVA'), ('asertividad', 'ASERTIVIDAD'), ('das_ansiedad', 'ANSIEDAD'), ('das_estres', 'ESTRÉS'), ('das_depresion', 'DEPRESIÓN'), ('ap_social', 'APOYO SOCIAL'), ('vi_pareja', 'VIOLENCIA DE PAREJA')], max_length=20)),
                ('low', models.TextField()),
                ('medium', models.TextField()),
                ('high', models.TextField()),
                ('audio_url', models.URLField()),
                ('video_url', models.URLField()),
                ('estado', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
