# Generated by Django 3.2.8 on 2021-11-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentirsebien', '0014_retroalimentacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retroalimentacion',
            old_name='audio_url',
            new_name='retro_audio_url',
        ),
        migrations.RenameField(
            model_name='retroalimentacion',
            old_name='high',
            new_name='retro_text',
        ),
        migrations.RenameField(
            model_name='retroalimentacion',
            old_name='video_url',
            new_name='retro_video_url',
        ),
        migrations.RemoveField(
            model_name='retroalimentacion',
            name='low',
        ),
        migrations.RemoveField(
            model_name='retroalimentacion',
            name='medium',
        ),
        migrations.AddField(
            model_name='retroalimentacion',
            name='nivel',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Low'), ('high', 'Low')], max_length=10),
        ),
    ]
