# Generated by Django 3.2.8 on 2021-11-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentirsebien', '0016_auto_20211105_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retroalimentacion',
            name='nivel',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
    ]
